### PR TITLE
Initial stab at github actions

### PR DESCRIPTION
**Pull request by akoutmos**
This PR is for #100. It switches over GenRMQ to use GitHub actions as opposed to Travis. The major benefit being that we can cache PLTs and deps for quicker CI runs.

Still a work in progress, but opening up the PR to test out the GH Action changes.

### CODE REVIEW

**Review by mkorszun — APPROVED** [review]
Nice 🥇 What is left?

**Comment by akoutmos** [comment]
@mkorszun Just need to validate that the PLT caching worked and that should be it. Perhaps also some additional static analysis tools?

**Comment by mkorszun** [comment]
would we also submit coveralls reports from gh actions?

**Comment by akoutmos** [comment]
I figured that all CI related steps would take place within GH actions? With the deps+plt cache, it should be all around faster i imagine?

**Comment by mkorszun** [comment]
@akoutmos sounds good 👍

**Review by vorce — APPROVED** [review]
Nice!

**Comment by akoutmos** [comment]
I think this PR is all set for now on my end. If there are any other validations that we want to add we can add those in future PRs.

**Comment by mkorszun** [comment]
great, feel free to merge it.

**Pull request merged**
