### PR TITLE
bump to amqp 1.0.x series

### PR DESCRIPTION
**Pull request by dch**
## Description

The current amqp dependency is pretty old, let's keep up to date with rabbitmq/pivotal upstream.

- update .gitignore after log testing
- bump mix.* as required
- correct minor spelling issues

```
Randomized with seed 659912
----------------
COV    FILE                                        LINES RELEVANT   MISSED
 81.5% lib/consumer.ex                               377       65       12
100.0% lib/message.ex                                 22        1        0
  0.0% lib/processor.ex                                6        0        0
 84.2% lib/publisher.ex                              173       19        3
100.0% lib/rabbit_case.ex                             75        1        0
[TOTAL]  82.6%
----------------
```

Superficial tests seem to pass on FreeBSD 12.0-CURRENT amd64 + RabbitMQ 3.7.5.

## Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by vorce** [comment]
Hey @dch - thanks for the PR. Will have a look asap.

**Comment by mkorszun** [comment]
@dch Looks good, just couple of small things:

* Let's disable `lagger` logs so we do not see them while running tests:

```
config :lager, handlers: [level: :critical]
```

Without this we would see:

```
13:32:25.498 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.209.0> exit with reason normal in context child_terminated
13:32:25.545 [info] Application lager started on node nonode@nohost
13:32:25.551 [info] Application xmerl started on node nonode@nohost
13:32:25.558 [info] Application ranch started on node nonode@nohost
13:32:25.560 [info] Application ranch_proxy_protocol started on node nonode@nohost
13:32:25.562 [info] Application recon started on node nonode@nohost
13:32:25.562 [info] Application rabbit_common started on node nonode@nohost
13:32:25.568 [info] Application amqp_client started on node nonode@nohost
13:32:25.568 [info] Application amqp started on node nonode@nohost
13:32:25.569 [info] Application gen_rmq started on node nonode@nohost
13:32:25.584 [info] Application ex_unit started on node nonode@nohost
```

* After upgrading `credo` we need to ensure we install `poison` for dev as well: 

from `{:poison, "~> 3.1", only: :test}` to `{:poison, "~> 3.1", only: [:dev, :test]}`

Currently it fails with:

```
Dependencies have diverged:
* poison (Hex package)
  the :only option for dependency poison

  > In mix.exs:
    {:poison, "~> 3.1", [env: :prod, repo: "hexpm", hex: "poison", only: :test, manager: :mix]}

  does not match the :only option calculated for

  > In deps/credo/mix.exs:
    {:poison, ">= 0.0.0", [only: :dev, env: :prod, hex: "poison", repo: "hexpm", optional: false]}

  Ensure you specify at least the same environments in :only in your dep
** (Mix) Can't continue due to errors on dependencies
```

**Comment by mkorszun** [comment]
We will also need to write similar migration notice -> https://github.com/pma/amqp/wiki/Upgrade-from-0.X-to-1.0#lager

**Comment by mkorszun** [comment]
Addressed in https://github.com/meltwater/gen_rmq/pull/22

**Comment by mkorszun** [comment]
@dch we have just release new version with `amqp` upgraded to `1.0.3`.

**Pull request closed without merging**
