### PR TITLE
Bump lib version to 3.0.0

### PR DESCRIPTION
**Pull request by mkorszun**
I believe we are ready 🎉 

## Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by spier** [comment]
@mkorszun besides bumping the version here, is there any other work that needs to be done to release a new version? e.g. something on https://hexdocs.pm/gen_rmq or elsewhere?

**Comment by mkorszun** [comment]
@spier yes, but it happens locally. Once this PR is merged will have to execute locally: `mix hex.publish` (this requires to authenticate against hex.pm)

**Comment by mkorszun** [comment]
The new version is on hex.pm. Kudos to @akoutmos for authoring main features. Thank you @spier, @vorce, and @Shemeikka for valuable comments, suggestions, and reviews 🎉 Great collaboration!

**Comment by akoutmos** [comment]
:tada:  Good work everyone :tada:

**Pull request merged**
