### PR TITLE
Fix some @specs

### PR DESCRIPTION
**Pull request by joaothallis**
## Description

I fixed with the help of Dialyxir: https://github.com/jeremyjh/dialyxir

Use built-in types described in: https://hexdocs.pm/elixir/typespecs.html

The type `GenRMQ.Message.t()` not work because not defined `@type t()`, using `GenRMQ.Message{}` works

## Checklist

- [ ] I have added unit tests to cover my changes.
- [x] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by mkorszun** [comment]
@joaothallis This is great! Would like to add Dialyxir here as well?

**Comment by joaothallis** [comment]
Yes, I'm going to add a commit with it.

**Comment by mkorszun** [comment]
@joaothallis How do we run it? Do we need anything in travis config so it is executed?

**Comment by joaothallis** [comment]
> How do we run it? 
```shell
mix dialyzer
```

> Do we need anything in travis config so it is executed?

For now I find it difficult to put in CI because it still has some warnings, after resolve it's not complicated to add Travis: https://blog.danielberkompas.com/2015/04/03/run-dialyzer-on-elixir-on-travis/

**Comment by vorce** [comment]
Thanks for your contribution @joaothallis ! 🎉

**Pull request merged**
