### PR TITLE
Upgrade amqp to version 1.0.3

### PR DESCRIPTION
**Pull request by mkorszun**
## Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by soundmonster** [comment]
I'm trying to upgrade to this version to test it with one of our phoenix apps, but it seems like latest Phoenix and amqp 1.0.x series conflict on ranch:
```
Failed to use "ranch" (version 1.3.2) because
  amqp (versions 1.0.0 to 1.0.3) requires ~> 1.4
  cowboy (version 1.1.2) requires ~> 1.3.2
  mix.lock specifies 1.3.2
```
Phoenix seems to need cowboy to be 1.x.x (latest is 1.1.2), but it specifies ranch 1.3.2.

Have you managed to make it work in a Phoenix app yet?

**Comment by vorce** [comment]
@soundmonster what did you do? Was it the `override: true` thing? If so we might want to mention it in the upgrade section of the README in this PR @mkorszun

**Comment by mkorszun** [comment]
@soundmonster @vorce yes, definitely will have to mention it. Will also check with couple of phoenix apps we have.

**Comment by soundmonster** [comment]
yep, the `override: true` thing with ranch 1.4

**Comment by mkorszun** [comment]
@soundmonster have you managed to silence lager as well?

**Comment by soundmonster** [comment]
yes, that worked! I've just used the snippet from your readme, reformatted it like this:
```elixir
```

**Comment by vorce** [comment]
That's nicer formatted for sure :D

**Comment by vorce** [comment]
Done @mkorszun LGTM - just made some small copy changes to the migrations wiki page.

**Pull request merged**
