### PR TITLE
Use handle_continue/2 for initializing

### LINKED ISSUE #108: Use handle_continue for non-blocking consumer/publisher setup
After bumping minimum required elixir version to 1.7 we are ready to use [handle_continue](https://hexdocs.pm/elixir/GenServer.html) callback:
https://medium.com/@tylerpachal/introduction-to-handle-continue-in-elixir-and-when-to-use-it-53ba5519cc17

### PR DESCRIPTION
**Pull request by vorce**
## Description

This makes the initialization of both publishers
and consumers safer.

Fixes #108

## Checklist

- [ ] I have added unit tests to cover my changes.
- [x] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by vorce** [comment]
Oh, I just found out that indeed `handle_continue/2` is only supported in OTP 21+:

> This callback is only supported on Erlang/OTP 21+.

https://hexdocs.pm/elixir/GenServer.html#c:handle_continue/2

**Comment by vorce** [comment]
This is of course a breaking change so we would also need to bump the major version once again :)

**Comment by mkorszun** [comment]
@vorce right, I have wrongly assumed that it is all about elixir >= 1.7 :/

**Comment by vorce** [comment]
@mkorszun should we close this? Not sure how much value it would give vs hassle to cut support for older OTP.

**Comment by vorce** [comment]
Closing this. The benefit of this is not worth the OTP version requirement.

**Pull request closed without merging**
