### PR TITLE
Ensure we are using absolute links in readme

### PR DESCRIPTION
**Pull request by mkorszun**
* Otherwise those links will be broken at [https://hexdocs.pm/gen_rmq/readme.html](https://hexdocs.pm/gen_rmq/readme.html), since `README.md` becomes a home page and `documentation` folder is not hosted on hex.pm.

* Update guide titles for consistency

* Replace documentation numbered list with a bulleted list

## Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by spier** [comment]
@mkorszun are you sure that some of the links in README.md would be broken when shown on hexdocs.pm?

This conversation here makes me think that this issue was fixed:
https://github.com/danschultzer/pow/issues/209

**Comment by spier** [comment]
Sorry, I closed this accidentally.

**Comment by mkorszun** [comment]
@spier they fixed the problem in https://github.com/danschultzer/pow/pull/211 by introducing custom markdown parser. There is no solution in ex_doc yet.

**Comment by spier** [comment]
Got it. What a pity!

Will review this in more detail now.

**Pull request merged**
