### PR TITLE
Switch to erlef/setup-beam to set up elixir and OTP for CI

### PR DESCRIPTION
**Pull request by vorce**
## Description

Switch from https://github.com/actions/setup-elixir to https://github.com/erlef/setup-beam for setting up elixir and OTP for CI. setup-elixir is not maintained anymore.

This should fix our broken CI pipeline I think.

## Checklist

- [ ] I have added unit tests to cover my changes.
- [x] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by vorce** [comment]
The static analysis fails, but I think we can tackle that in a separate PR

**Review by mkorszun — APPROVED** [review]
Looks good - thanks for the work 👍

**Review by mkorszun — APPROVED** [review]

**Comment by vorce** [comment]
@mkorszun I'm not authorized to merge :P

**Comment by mkorszun** [comment]
@vorce right, missed that. Merged 👌

**Pull request merged**
