### PR TITLE
mix: use updated amqp latest rabbitmq_common

### PR DESCRIPTION
**Pull request by dch**
## Description

Update to amqp 1.4, which then pulls in rabbit_common 3.8.2, and uses a much simpler dependency list which should make everybody's GenRMQ "Do The Right Thing" and not need constant pinning of all deps inside of deps.

## Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have improved the code quality of this repo. (refactoring, or reduced number of static analyser issues)
- [x] I have updated the documentation accordingly

This warrants further testing on a variety of OTP, Elixir, & RabbitMQ versions.

### CODE REVIEW

**Comment by dch** [comment]
LGTM, grabs the 1.4.0 and 3.8.2 bits from upstream too now

**Comment by mkorszun** [comment]
@dch looks good, although we stop supporting certain OTP versions - check failed builds.

**Comment by dch** [comment]
@mkorszun what's the plan here - do you care about the obsolete/older OTP versions? upstream doesn't support them which means no VM fixes for critical issues. The choice is yours as presumably meltwater has some internal dependencies.

**Comment by vorce** [comment]
@mkorszun I think we should drop support for OTP 20 tbh.

**Comment by mkorszun** [comment]
@vorce @dch yes, makes sense. There will be the last 2.x.x release this or next week. Then we can start working on version 3.x.x, dropping support for OTP20. We can also start using `handle_continue` :)

**Comment by dch** [comment]
already taken care of on master

**Pull request closed without merging**
